title   : Nitro
homepage: http://www.nitroproject.org
author  : George K. Moschovitis
license : BSD
brief   : Everything you need to create Web 2.0 applications with Ruby and Javascript.
description:
  Nitro provides everything you need to develop professional Web
  applications using Ruby and Javascript. Nitro redefines Rapid 
  Application Development by providing a clean, yet efficient API, 
  a layer of domain specific languages implemented on top of 
  Ruby and the most powerful and elegant object relational 
  mapping solution available everywhere. Nitro is Web 2.0 ready, 
  featuring excellent support for AJAX, XML, Syndication while 
  staying standards compliant.

executables: [ nitro ]

dependency:
  - [   og, = 0.50.0 ]
  - [  raw, = 0.50.0 ]
  - [ glue, = 0.50.0 ]

document: true

index_file: main.rb

lib_path:
  - lib/nitro

gem_path:
  - lib
